name: jb
description: JBuild front-end. A modern Java build system that leverages Dartle to make building Java projects easy.
version: 0.14.0
repository: https://github.com/renatoathaydes/jb
environment:
  sdk: '>=3.9.0 <4.0.0'
publish_to: none
dependencies:
  path: ^1.8.2
  io: ^1.0.4
  dartle: ^0.34.0
  args: ^2.3.1
  logging: ^1.0.0
  collection: ^1.19.0
  yaml: ^3.1.1
  file: ^7.0.0
  isolate_current_directory: ^2.2.0
  archive: ^4.0.7
  xml: ^6.2.2
  actors: ^0.11.0
  conveniently: ^1.2.0
  structured_async: ^0.3.2
  crypto: ^3.0.3
  schemake: ^0.6.6
dev_dependencies:
  build_runner: ^2.4.11
  lints: ^6.0.0
  test: ^1.25.8

executables:
  jb: jbuild_cli
